### ISSUE TITLE
Intellij IDEA编辑器中的中英字体可以单独设置

### ISSUE THREAD

**Issue by Glowin** [Damao/Intellij-IDEA-F2E#2]
这篇文章就实现了编辑器中的英文为monaco，中文为微软雅黑，见下图

![字体](http://s.willerce.com/uploads/2012/10/intellij-ide-fontconfig-screen2.png)

博客链接 [IDEA 字体美化](http://willerce.com/post/intellij-ide-fontconfig)

**Comment by XinyuChan** [comment]
Cannot proxy the given URL。
能再发遍么谢谢。
